Week 1 Quiz Submission from whu8-stat660
stat660-f18/course-questions-wiki pull request #4
Opened 2018-08-25 22:15 UTC by whu8-stat660

2018-08-26 16:05 UTC, prof-lankham requested changes
Please review all instructions, update the PR, and DM the instructor in Slack with the PR URL when ready for re-evaluation.

2018-08-26 16:05 UTC, prof-lankham commented on week-01/README.md
> +[Chapter 1 Performing Queries Using PROC SQL, Problem 4]
Please ask questions whose answers would help you better understand the concepts in the specified problems only. Please also review https://www.csueastbay.edu/academic/academic-policies/academic-dishonesty.html

2018-08-26 16:05 UTC, prof-lankham commented on week-01/README.md
All contributions should directly follow their corresponding problem header, rather than have a blank line between them.

2018-08-26 16:05 UTC, prof-lankham commented on week-01/README.md
> +*Reference*:https://www.datasciencecentral.com/profiles/blogs/r-python-or-sas-which-one-should-you-learn-first
If giving references, please include in the same paragraph as the answer, rather than start a new paragraph

2018-08-26 16:05 UTC, prof-lankham commented on week-01/README.md
> +*Question (whu8-stat660): How to import data into SAS?
This is not relevant to the specified recipe.

2018-08-26 18:41 UTC, prof-lankham commented on week-01/README.md
> +*Question (whu8-stat660): Can we create project-group-discussion channel to discuss the group project?
A space is needed after the asterisk for each contribution.

2018-08-26 18:48 UTC, prof-lankham commented on week-01/README.md
> +*Question (whu8-stat660): How to import data into SAS?
Please ask questions whose answers would help you better understand the concepts in the recipe.

2018-08-26 20:24 UTC, whu8-stat660 commented on week-01/README.md
> +[Chapter 1 Performing Queries Using PROC SQL, Problem 4]
Thank you, professor! 
The reason why I changed the title is that in the instruction it says " In particular, each question/answer should have the following format:
[<Problem Source with Chapter, or Full Recipe Name>]
∗ Question (<your−f u ll −github−username >): <q u e s ti o n te x t>
∗ Answer (<your−f u l l −github−username >): <answer te x t>"
So I put the problem source on this question,  but I think I misunderstood it according to your response.  However, I did read through the first chapter, and this question is actually my real question when I practice with SQL queries.  If this question doesn't meet the requirement, I can modify it.

2018-08-27 02:42 UTC, prof-lankham commented on week-01/README.md
> +[Chapter 1 Performing Queries Using PROC SQL, Problem 4]
In general, PR comments are not monitored. Please use Slack to discuss feedback.

2018-08-27 02:45 UTC, prof-lankham requested changes
Please review all instructions, update the PR, and DM the instructor in Slack with the PR URL when ready for re-evaluation.

2018-08-27 02:45 UTC, prof-lankham commented on week-01/README.md
> +SAS is extremely efficient at sequential data access, and database access through SQL is well integrated. The drag-and-drop interface makes it easy for you to create better statistical models quickly
Please do not embed line breaks in contribution components.

2018-08-27 02:45 UTC, prof-lankham commented on week-01/README.md
> +If expression-1 is false, SAS will move to the next ELSE IF line and check expression-2.If expression-2 is true, SAS executes statement-2 and does NOT check the remaining ELSE IF statements. SAS will
Please do not embed line breaks in contribution components.

2018-08-27 02:45 UTC, prof-lankham commented on week-01/README.md
> +The same process will continue until SAS gets to the last ELSE statement. This last ELSE statement does not have an expression to check, so SAS will execute the THEN statement whenever this line is r
Please do not embed line breaks in contribution components.

2018-08-27 02:45 UTC, prof-lankham commented on week-01/README.md
> +The same process will continue until SAS gets to the last ELSE statement. This last ELSE statement does not have an expression to check, so SAS will execute the THEN statement whenever this line is r
Please also put parenthesis around the reference, e.g., " (*Reference*: https://analytics.ncsu.edu/sesug/2013/CC-18.pdf)"

2018-08-27 02:45 UTC, prof-lankham commented on week-01/README.md
> +SAS is extremely efficient at sequential data access, and database access through SQL is well integrated. The drag-and-drop interface makes it easy for you to create better statistical models quickly
Please also put parenthesis around the reference, e.g., " (*Reference*: https://www.datasciencecentral.com/profiles/blogs/r-python-or-sas-which-one-should-you-learn-first)"

2018-08-28 15:39 UTC, merged